In [2]:
import torch


# context.transpose(1, 2).contiguous().view
# Tensor.contiguous(memory_format=torch.contiguous_format) → Tensor
# Returns a contiguous in memory tensor containing the same data as self tensor. If self tensor is already in the specified memory format, this function returns the self tensor.

# masked_fill_

# seq_k.data.eq(0).unsqueeze(1)
# seq_len = x.size(1)


# torch.matmul
# nn.LayerNorm(d_model)

In [32]:
# 1. 初始化
x = torch.tensor(2, 5)
x = torch.tensor([1, 2, 3])
x = torch.randn(2, 3)
pos = torch.arange(2, dtype=torch.long)

print(pos,pos.shape)
pos = pos.unsqueeze(0)
print(pos,pos.shape)
# print(pos.expand_as(x) )


tensor([0, 1]) torch.Size([2])
tensor([[0, 1]]) torch.Size([1, 2])


In [33]:
# 2.增、删、改 tensor元素
x = torch.tensor([1, 2, 3])
print(x)
x = x.repeat(4, 2)
print(x)

tensor([1, 2, 3])
tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])


In [ ]:
# 3. 升降维,转置，打平，

In [ ]:
# 4. 索引

In [37]:
m = torch.tensor([[1,0,0],[0,1,0]])
x = torch.tensor([[1,2,3],[4,5,6]])
x.masked_fill_(m, -1e9)


tensor([[-1000000000,           2,           3],
        [          4, -1000000000,           6]])

In [18]:
x = torch.tensor([1, 2, 3, 4])
print(x.shape)
print(torch.unsqueeze(x, 0)) 
print(torch.unsqueeze(x, 1)) 
print(torch.unsqueeze(x, 0).shape) 
print(torch.unsqueeze(x, 1).shape) 

# A dim value within the range [-input.dim() - 1, input.dim() + 1) can be used. 
# Negative dim will correspond to unsqueeze() applied at dim = dim + input.dim() + 1.
                              
x = torch.tensor([[1],
        [2],
        [3],
        [4]])
print("~~~~~")
print(x.shape)
print(torch.unsqueeze(x, 0).shape)
print(torch.unsqueeze(x, 1).shape)
print(torch.unsqueeze(x, -2).shape)

torch.Size([4])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([1, 4])
torch.Size([4, 1])
~~~~~
torch.Size([4, 1])
torch.Size([1, 4, 1])
torch.Size([4, 1, 1])
torch.Size([4, 1, 1])


In [20]:
x = torch.tensor([[1], [2], [3]])
print(x.size())

print(x.expand(3, 4)) #3行4列
print(x.expand(-1, 4))   # -1 means not

# x.expand_as() 等同expand

torch.Size([3, 1])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])


In [21]:
t = torch.tensor([[1, 2], [3, 4]])
torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 1],
        [4, 3]])

In [36]:
x = torch.randn(4, 4)
y = x.view(16)
print(y,y.size())
# print(x.transpose(1, 2) )

tensor([ 2.0502,  0.9128,  0.3904, -1.0539, -0.3555,  0.3123,  1.3060, -0.4311,
        -0.3213,  1.1517, -1.5596,  0.7091, -1.6580, -0.0346, -0.5737,  0.6815]) torch.Size([16])


In [35]:
x = torch.randn(2, 3)
print(x,x.size())
torch.transpose(x, 0, 1)

# transpose, 负数意思是从后往前数

tensor([[ 0.2202,  1.9603, -0.9585],
        [-0.2536,  0.0324, -1.6509]]) torch.Size([2, 3])


tensor([[ 0.2202, -0.2536],
        [ 1.9603,  0.0324],
        [-0.9585, -1.6509]])

![矩阵点乘](images/dot_product.webp)

In [46]:
tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[5],[6]])
print(tensor1.shape,tensor2.shape)

#维度变化：[a,b] * [b,c] = [a,c]
ret = torch.matmul(tensor1, tensor2)
ret1 = tensor1.matmul(tensor2)
print(ret1) 

ret2 = tensor1 * tensor2 #注意差别
print(tensor1.shape,tensor2.shape,ret.shape)
print(ret)
print(ret2)

# https://pytorch.org/docs/master/generated/torch.matmul.html?highlight=matmul#torch.matmul

torch.Size([2, 2]) torch.Size([2, 1])
tensor([[17],
        [39]])
torch.Size([2, 2]) torch.Size([2, 1]) torch.Size([2, 1])
tensor([[17],
        [39]])
tensor([[ 5, 10],
        [18, 24]])


In [ ]:
# https://pytorch.org/docs/master/generated/torch.gather.html?highlight=gather#torch.gather
