介绍 query doc 语义相关性

![语义相似度](./images/qu_rel.png)
Query和Doc经过一个表示层，将输入转换为2个向量，计算这两个向量的cos距离，再过一个softmax，使用交叉熵作为损失函数。
考虑一个query下召回的doc的相对相似度，作为一个排序问题，可以借鉴前面提到的point-wise,paire-wise,list-wise的思想。

https://github.com/JepsonWong/Text_Matching


In [6]:
import torch
import torch.nn.functional as F

# 两个向量的相似度度量
# 1.余弦相似度，两个特征在经过L2归一化之后的矩阵内积。取值范围[-1,1]，要计算的连个向量维度必须一致
# https://pytorch.org/docs/master/generated/torch.nn.functional.cosine_similarity.html#torch.nn.functional.cosine_similarity
input1 = torch.randn(3, 2)
print(input1)
input2 = torch.randn(3, 2)
print(input2)
output = F.cosine_similarity(input1, input2)
print(output)

tensor([[-0.2423,  1.2422],
        [-1.1246,  1.2047],
        [ 0.7806, -0.2597]])
tensor([[-0.8846, -0.2148],
        [-0.2815,  0.3075],
        [ 0.6451,  0.8955]])
tensor([-0.0455,  1.0000,  0.2985])


In [ ]:
# https://github.com/nishnik/Deep-Semantic-Similarity-Model-PyTorch/blob/master/cdssm.py
# 