In [1]:
import numpy as np
np.random.seed(0) 

data_count = 3
w,b = 5,3
x1 = np.random.rand(data_count)
y1 = w*x1 + b + np.random.rand(data_count)*5
print("x1,y1:",x1,y1)
print("x1,y1 reshape:", x1.reshape((-1, 1)).shape, x1.reshape((-1, 1)))

x1 = x1.reshape((-1, 1))
y1 = y1.reshape((-1, 1))
label_1 = np.ones_like(x1)
print(label_1)

print(np.concatenate((label_1,x1,y1),axis=1))


x2 = np.random.rand(3)
y2 = w*x2 + b - np.random.rand(data_count)*5
print("x2,y2:",x2,y2)

x0 = x2.reshape((-1, 1))
y0 = y2.reshape((-1, 1))
label_0 = np.zeros_like(x0)

print(np.concatenate((label_0,x0,y0),axis=1))

x1,y1: [0.5488135  0.71518937 0.60276338] [8.46848343 8.69422083 9.24328745]
x1,y1 reshape: (3, 1) [[0.5488135 ]
 [0.71518937]
 [0.60276338]]
[[1.]
 [1.]
 [1.]]
[[1.         0.5488135  8.46848343]
 [1.         0.71518937 8.69422083]
 [1.         0.60276338 9.24328745]]
x2,y2: [0.43758721 0.891773   0.96366276] [3.27072846 3.50023981 5.1738392 ]
[[0.         0.43758721 3.27072846]
 [0.         0.891773   3.50023981]
 [0.         0.96366276 5.1738392 ]]


In [2]:
def generate_data(w,b,data_count,labels=0):
    x = np.random.rand(data_count)
    print(x.shape,x)
    y = (w*x + b + np.random.rand(data_count)*5).reshape((-1, 1)) 
    print(y.shape,y)
#     x = x.reshape((-1, 1))
    label = np.ones_like(y) if labels==1 else np.zeros_like(y)
    print(label.shape)
    return np.concatenate((label,np.reshape(x,(-1, 1)),y),axis=1)

data1 = generate_data(w,b,data_count,0)
data2 = generate_data(w,b,data_count,1)
data_all = np.concatenate((data1,data2),axis=0)
print(data_all)
np.random.shuffle(data_all)
print(data_all)

(3,) [0.56804456 0.92559664 0.07103606]
(3, 1) [[6.2758693 ]
 [7.72907518]
 [7.51827952]]
(3, 1)
(3,) [0.77815675 0.87001215 0.97861834]
(3, 1) [[10.88657658]
 [ 9.65745755]
 [11.79573759]]
(3, 1)
[[ 0.          0.56804456  6.2758693 ]
 [ 0.          0.92559664  7.72907518]
 [ 0.          0.07103606  7.51827952]
 [ 1.          0.77815675 10.88657658]
 [ 1.          0.87001215  9.65745755]
 [ 1.          0.97861834 11.79573759]]
[[ 1.          0.97861834 11.79573759]
 [ 0.          0.07103606  7.51827952]
 [ 1.          0.77815675 10.88657658]
 [ 1.          0.87001215  9.65745755]
 [ 0.          0.92559664  7.72907518]
 [ 0.          0.56804456  6.2758693 ]]


In [3]:
x2 = np.random.rand(data_count).reshape((-1, 1))
print(x2.shape,x2)
y2 = (w*x2 + b + (np.random.rand(data_count)*5).reshape(-1, 1))
print(y2.shape,y2)
print(np.concatenate((x2,y2),axis=1))

(3, 1) [[0.75861562]
 [0.10590761]
 [0.47360042]]
(3, 1) [[7.72473984]
 [7.21412892]
 [6.45075387]]
[[0.75861562 7.72473984]
 [0.10590761 7.21412892]
 [0.47360042 6.45075387]]


In [4]:
x = np.random.rand(data_count)
ret1 = np.sum(x) / x.shape[0]
print(ret1)
ret2 = np.mean(x)
print(ret1)


0.2030113494607831
0.2030113494607831


In [10]:
a = ['1','2']
b = list(map(lambda x:x+2, map(float,a)))
print(b)

x = np.zeros(4)
x[3]=1
print(x)

t = np.zeros(4)
t[3]=1
print(t)

t = np.zeros(4)[3]=1
print(t) 

[3.0, 4.0]
[0. 0. 0. 1.]
[0. 0. 0. 1.]
1
